---
- hosts: localhost
  connection: local
  roles:
    - docker-run

  vars_files:
    - variables.yml
    - secrets.yml

  vars:
    repo_proxy: False
    docker_container_prefix: "mon-"
    docker_container_network: monitoring
    docker_container_volume:
        - prometheus_data
        - grafana_data
        - db_data

    docker_container:
      - name: pgdb
        path: ./postgres
        restart: always
        volumes:
          - "db_data:/var/lib/postgresql/data"
        env:
          "{{ postgres_variables }}"
        networks: "{{ docker_container_network }}"
        alias:
          - postgres

      - name: alertmanager
        image: prom/alertmanager
        ports:
          - 9093:9093
        command:
          - '-config.file=/etc/alertmanager/config.yml'
          - '-storage.path=/alertmanager'
        hosts:
            "{{ prometheus_hosts }}"
        volumes:
          - ./alertmanager/:/etc/alertmanager/
        networks: "{{ docker_container_network }}"

      - name: blackbox
        image: prom/blackbox-exporter
        volumes:
          - ./blackbox/:/config/
        command:
          - '--config.file=/config/blackbox.yml'
        ports:
          - 9115:9115
        networks: "{{ docker_container_network }}"
        files:
          - src: ./templates/blackbox.yml.j2
            dest: ./prometheus/blackbox.yml
            owner: root

      - name: prometheus
        image: prom/prometheus
        ports:
          - 9090:9090
        command:
          - '-config.file=/etc/prometheus/prometheus.yml'
          - '-storage.local.path=/prometheus'
          - '-alertmanager.url=http://alertmanager:9093'
        hosts:
          "{{ prometheus_hosts }}"
        volumes:
          - ./prometheus/:/etc/prometheus/
          - prometheus_data:/prometheus
        networks: "{{ docker_container_network }}"
        files:
          - src: ./templates/prometheus.yml.j2
            dest: ./prometheus/prometheus.yml
            owner: root
          - src: ./templates/prometheus.targets.j2
            dest: ./prometheus/targets.yml
            owner: root

      - name: grafana
        image: grafana/grafana
        ports:
          - 3000:3000
        volumes:
          - grafana_data:/var/lib/grafana
        env:
          "{{ grafana_variables }}"
        networks: "{{ docker_container_network }}"

